apiVersion: v1
kind: Service
metadata:
  name: counter-server-gateway
spec:
  selector:
    app: counter-server-gateway
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer
